name: deploy
on: 
  push:
    branches:
      - master

jobs:
  audit:
    uses: './.github/workflows/audit.yaml'
  #quality:
    #uses: './.github/workflows/quality.yaml'
  #tests:
    #needs: [audit, quality]
    #uses: './.github/workflows/test.yaml'
  deploy:
    name: deploy
    needs: [audit]
    runs-on: ubuntu-latest
    steps:
      - name: execute ssh command
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/hiladang_character
            git pull origin master --rebase
            make deploy
