name: Quality Analysis
on:
  workflow_call:
  push:
    branches-ignore:
      - master
      - test
  pull_request:
    branches-ignore:
      - master
      - test
      
jobs:
  quality:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.4-composer-${{ hashFiles('**/composer.json')}}
          restore-keys: |
            php8.4-composer-latest-

      - name: Update composer
        run: composer self-update

      - name: install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Quality Analysis
        run: composer app:code-quality
